#!/bin/bash

if (( $# < 2 )); then
  echo "$(basename $0) TOKEN USERNAME"
  exit
fi
TOKEN=$1
USERNAME=$2

# Mengatur halaman awal dan per_page
PAGE=1
PER_PAGE=100

# Fungsi untuk menunggu hingga rate limit direset
wait_for_rate_limit_reset() {
  echo "Mencapai batas API, menunggu hingga rate limit direset..."
  while :; do
    rate_limit=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit)
    remaining=$(echo "$rate_limit" | jq .rate.remaining)
    reset_time=$(echo "$rate_limit" | jq .rate.reset)
    if [[ $remaining -gt 0 ]]; then
      echo "Rate limit tersedia kembali: $remaining permintaan tersisa."
      break
    fi
    current_time=$(date +%s)
    wait_time=$((reset_time - current_time))
    echo "Menunggu $wait_time detik hingga rate limit direset..."
    sleep $wait_time
  done
}



while true; do
  # Mendapatkan daftar pengikut (100 per halaman)
  response=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/users/$USERNAME/followers?per_page=$PER_PAGE&page=$PAGE")
  # Cek rate limit
  rate_limit=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit)
  remaining=$(echo "$rate_limit" | jq .rate.remaining)
  if [[ $remaining -le 0 ]]; then
    wait_for_rate_limit_reset
  else
    echo "Masih ada $remaining permintaan tersisa. Melanjutkan..."
  fi
  # Mengambil daftar login pengikut
  followers=$(echo "$response" | jq -r '.[].login')
  # Jika tidak ada pengikut, keluar dari loop
  if [ -z "$followers" ]; then
    echo "Tidak ada pengikut lebih lanjut atau Anda telah mengikuti semua pengikut."
    break
  fi
  # Mengikuti setiap pengikut
  for follower in $followers; do
    echo "Mengikuti kembali: $follower"
    curl -s -X PUT -H "Authorization: token $TOKEN" "https://api.github.com/user/following/$follower"
  done
  # Cek apakah ada halaman berikutnya
  link_header=$(curl -s -I -H "Authorization: token $TOKEN" "https://api.github.com/users/$USERNAME/followers?per_page=$PER_PAGE&page=$PAGE" | grep -i "Link:")
  if [[ "$link_header" =~ "rel=\"next\"" ]]; then
    # Jika ada halaman berikutnya, lanjutkan ke halaman berikutnya
    ((PAGE++))
  else
    # Jika tidak ada halaman berikutnya, keluar dari loop
    break
  fi
done

echo "Selesai mengikuti kembali semua pengikut."
